p8105_hw5_gw2442
================
2022-11-10

``` r
library(tidyverse)
```

    ## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
    ## ✔ ggplot2 3.3.6      ✔ purrr   0.3.4 
    ## ✔ tibble  3.1.8      ✔ dplyr   1.0.10
    ## ✔ tidyr   1.2.0      ✔ stringr 1.4.1 
    ## ✔ readr   2.1.2      ✔ forcats 0.5.2 
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()

``` r
library(rvest)
```

    ## 
    ## Attaching package: 'rvest'
    ## 
    ## The following object is masked from 'package:readr':
    ## 
    ##     guess_encoding

``` r
library(broom)
set.seed(1)
knitr::opts_chunk$set(echo = TRUE)
```

## Problem 1

Importing data

``` r
problem_1 = 
list.files(path = "/data")
```

## Problem 2

Importing and describing raw data:

``` r
homicide_data = read_csv(file = "./data/homicide-data.csv") %>%
  janitor::clean_names()
```

    ## Rows: 52179 Columns: 12
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (9): uid, victim_last, victim_first, victim_race, victim_age, victim_sex...
    ## dbl (3): reported_date, lat, lon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
skimr::skim(homicide_data)
```

|                                                  |               |
|:-------------------------------------------------|:--------------|
| Name                                             | homicide_data |
| Number of rows                                   | 52179         |
| Number of columns                                | 12            |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_   |               |
| Column type frequency:                           |               |
| character                                        | 9             |
| numeric                                          | 3             |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ |               |
| Group variables                                  | None          |

Data summary

**Variable type: character**

| skim_variable | n_missing | complete_rate | min | max | empty | n_unique | whitespace |
|:--------------|----------:|--------------:|----:|----:|------:|---------:|-----------:|
| uid           |         0 |             1 |   9 |  10 |     0 |    52179 |          0 |
| victim_last   |         0 |             1 |   1 |  20 |     0 |    12687 |          0 |
| victim_first  |         0 |             1 |   1 |  28 |     0 |    16640 |          0 |
| victim_race   |         0 |             1 |   5 |   8 |     0 |        6 |          0 |
| victim_age    |         0 |             1 |   1 |   7 |     0 |      102 |          0 |
| victim_sex    |         0 |             1 |   4 |   7 |     0 |        3 |          0 |
| city          |         0 |             1 |   5 |  14 |     0 |       50 |          0 |
| state         |         0 |             1 |   2 |   2 |     0 |       28 |          0 |
| disposition   |         0 |             1 |  14 |  21 |     0 |        3 |          0 |

**Variable type: numeric**

| skim_variable | n_missing | complete_rate |        mean |         sd |          p0 |         p25 |         p50 |         p75 |          p100 | hist  |
|:--------------|----------:|--------------:|------------:|-----------:|------------:|------------:|------------:|------------:|--------------:|:------|
| reported_date |         0 |             1 | 20130899.16 | 1123419.63 | 20070101.00 | 20100318.00 | 20121216.00 | 20150911.00 | 201511105\.00 | ▇▁▁▁▁ |
| lat           |        60 |             1 |       37.03 |       4.35 |       25.73 |       33.77 |       38.52 |       40.03 |         45.05 | ▁▅▅▇▅ |
| lon           |        60 |             1 |      -91.47 |      13.75 |     -122.51 |      -96.00 |      -87.71 |      -81.76 |        -71.01 | ▃▁▃▇▅ |

The CSV file was downloaded from the GitHub repository, imported, and
cleaned. The dataset `homicide_data` has 52,179 rows and 12 columns. The
dataset contains information on the homicide ID number, reported date,
the victim’s first and last name, race, age, sex, location of homicide
(including city, state, longtidue, and latitude), and disposition of the
case. While there are 0 missing variables for variables `uid`,
`victim_last`, `victim_first`, `victim_race`, `victim_age`,
`victim_sex`, `city`, `state`, `disposition`, and `reported date`, there
are 60 missing variables for `lat` and `lon`.

Creating variable `city_state`:

``` r
homicide_data$city_state <- as.character(paste(homicide_data$city, homicide_data$state, sep = "_"))
```

Creating variable `unsolved_homicide`:

The variable `unsolved_homicide` was created. Those with the disposition
“Closed without arrest” or “Open/No arrest” were categorised as an
unsolved homicide and were therefore given a value of 1 in the variable
`unsolved_homicide`. Those with the disposition “Closed by arrest” were
categorised as a solved homicide and were therefore given a value of 0
in the variable `unsolved_homicide`.

``` r
homicide_data %>%
  mutate(
    unsolved_homicide = 
      if_else(disposition == "Closed by arrest", 0, 1)
  ) %>%
  group_by(city_state, unsolved_homicide) %>%
  summarise(n_obs = n()) %>%
  spread(key= unsolved_homicide, value = n_obs) %>%
  knitr::kable()
```

    ## `summarise()` has grouped output by 'city_state'. You can override using the
    ## `.groups` argument.

| city_state        |    0 |    1 |
|:------------------|-----:|-----:|
| Albuquerque_NM    |  232 |  146 |
| Atlanta_GA        |  600 |  373 |
| Baltimore_MD      | 1002 | 1825 |
| Baton Rouge_LA    |  228 |  196 |
| Birmingham_AL     |  453 |  347 |
| Boston_MA         |  304 |  310 |
| Buffalo_NY        |  202 |  319 |
| Charlotte_NC      |  481 |  206 |
| Chicago_IL        | 1462 | 4073 |
| Cincinnati_OH     |  385 |  309 |
| Columbus_OH       |  509 |  575 |
| Dallas_TX         |  813 |  754 |
| Denver_CO         |  143 |  169 |
| Detroit_MI        | 1037 | 1482 |
| Durham_NC         |  175 |  101 |
| Fort Worth_TX     |  294 |  255 |
| Fresno_CA         |  318 |  169 |
| Houston_TX        | 1449 | 1493 |
| Indianapolis_IN   |  728 |  594 |
| Jacksonville_FL   |  571 |  597 |
| Kansas City_MO    |  704 |  486 |
| Las Vegas_NV      |  809 |  572 |
| Long Beach_CA     |  222 |  156 |
| Los Angeles_CA    | 1151 | 1106 |
| Louisville_KY     |  315 |  261 |
| Memphis_TN        | 1031 |  483 |
| Miami_FL          |  294 |  450 |
| Milwaukee_wI      |  712 |  403 |
| Minneapolis_MN    |  179 |  187 |
| Nashville_TN      |  489 |  278 |
| New Orleans_LA    |  504 |  930 |
| New York_NY       |  384 |  243 |
| Oakland_CA        |  439 |  508 |
| Oklahoma City_OK  |  346 |  326 |
| Omaha_NE          |  240 |  169 |
| Philadelphia_PA   | 1677 | 1360 |
| Phoenix_AZ        |  410 |  504 |
| Pittsburgh_PA     |  294 |  337 |
| Richmond_VA       |  316 |  113 |
| Sacramento_CA     |  237 |  139 |
| San Antonio_TX    |  476 |  357 |
| San Bernardino_CA |  105 |  170 |
| San Diego_CA      |  286 |  175 |
| San Francisco_CA  |  327 |  336 |
| Savannah_GA       |  131 |  115 |
| St. Louis_MO      |  772 |  905 |
| Stockton_CA       |  178 |  266 |
| Tampa_FL          |  113 |   95 |
| Tulsa_AL          |    1 |   NA |
| Tulsa_OK          |  390 |  193 |
| Washington_DC     |  756 |  589 |

``` r
homicide_data %>%
  group_by(city_state) %>%
  summarise(n_obs = n()) %>%
  knitr::kable()
```

| city_state        | n_obs |
|:------------------|------:|
| Albuquerque_NM    |   378 |
| Atlanta_GA        |   973 |
| Baltimore_MD      |  2827 |
| Baton Rouge_LA    |   424 |
| Birmingham_AL     |   800 |
| Boston_MA         |   614 |
| Buffalo_NY        |   521 |
| Charlotte_NC      |   687 |
| Chicago_IL        |  5535 |
| Cincinnati_OH     |   694 |
| Columbus_OH       |  1084 |
| Dallas_TX         |  1567 |
| Denver_CO         |   312 |
| Detroit_MI        |  2519 |
| Durham_NC         |   276 |
| Fort Worth_TX     |   549 |
| Fresno_CA         |   487 |
| Houston_TX        |  2942 |
| Indianapolis_IN   |  1322 |
| Jacksonville_FL   |  1168 |
| Kansas City_MO    |  1190 |
| Las Vegas_NV      |  1381 |
| Long Beach_CA     |   378 |
| Los Angeles_CA    |  2257 |
| Louisville_KY     |   576 |
| Memphis_TN        |  1514 |
| Miami_FL          |   744 |
| Milwaukee_wI      |  1115 |
| Minneapolis_MN    |   366 |
| Nashville_TN      |   767 |
| New Orleans_LA    |  1434 |
| New York_NY       |   627 |
| Oakland_CA        |   947 |
| Oklahoma City_OK  |   672 |
| Omaha_NE          |   409 |
| Philadelphia_PA   |  3037 |
| Phoenix_AZ        |   914 |
| Pittsburgh_PA     |   631 |
| Richmond_VA       |   429 |
| Sacramento_CA     |   376 |
| San Antonio_TX    |   833 |
| San Bernardino_CA |   275 |
| San Diego_CA      |   461 |
| San Francisco_CA  |   663 |
| Savannah_GA       |   246 |
| St. Louis_MO      |  1677 |
| Stockton_CA       |   444 |
| Tampa_FL          |   208 |
| Tulsa_AL          |     1 |
| Tulsa_OK          |   583 |
| Washington_DC     |  1345 |

The city with the most homicides was Chicago, IL with 5,535 homicides -
1,462 of which were solved and 4,073 were unsolved.

## Problem 3

Setting the design elements for the model `problem_3_mean_p`:

``` r
problem_3_mean_p = function(samp_size = 30, mu, sigma = 5) {
  
  sim_data = 
    tibble(
    x = rnorm(n = samp_size, mean = mu, sd = sigma),
  )
  
  sim_data %>% 
    t.test() %>%
    tidy() %>%
    select(estimate, p.value)
    
}
```

Generating 5000 datasets from the model with mu = (0, 1, 2, 3, 4, 5, 6):

``` r
n_list = 
  list(
    "mu = 0" = 0,
    "mu = 1" = 1,
    "mu = 2" = 2,
    "mu = 3" = 3,
    "mu = 4" = 4,
    "mu = 5" = 5,
    "mu = 6" = 6
  )

problem_3_output = vector("list", length = 7)

for (i in 1:7) {
  
  problem_3_output[[i]] = 
    rerun(5000, problem_3_mean_p(mu = n_list[[i]])) %>%
    bind_rows()
  
}
```

Creating a plot to demonstrate the proportion of times the null was
rejected (the power of the test) on the y axis and the true value of mu
on the x axis.

``` r
problem_3_df = 
  expand_grid(
    sample_size = 30,
    iter = 1:5000
  ) %>%
  mutate(
    estimate_df = map(sample_size, problem_3_mean_p)) %>%
  unnest(estimate_df)
```
